[[redirects]]
  from = "https://itstechnova.netlify.app/*"
  to = "https://www.itstechnova.com/:splat"

[[redirects]]
  from = "https://www.itstechnova.org/*"
  to = "https://www.itstechnova.com/:splat"